// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: qrgen.proto

package qrgen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// QrGeneratorClient is the client API for QrGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QrGeneratorClient interface {
	GenerateQR(ctx context.Context, in *QrGenRequest, opts ...grpc.CallOption) (*QrImage, error)
}

type qrGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewQrGeneratorClient(cc grpc.ClientConnInterface) QrGeneratorClient {
	return &qrGeneratorClient{cc}
}

func (c *qrGeneratorClient) GenerateQR(ctx context.Context, in *QrGenRequest, opts ...grpc.CallOption) (*QrImage, error) {
	out := new(QrImage)
	err := c.cc.Invoke(ctx, "/qrgen.QrGenerator/GenerateQR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QrGeneratorServer is the server API for QrGenerator service.
// All implementations must embed UnimplementedQrGeneratorServer
// for forward compatibility
type QrGeneratorServer interface {
	GenerateQR(context.Context, *QrGenRequest) (*QrImage, error)
	mustEmbedUnimplementedQrGeneratorServer()
}

// UnimplementedQrGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedQrGeneratorServer struct {
}

func (UnimplementedQrGeneratorServer) GenerateQR(context.Context, *QrGenRequest) (*QrImage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQR not implemented")
}
func (UnimplementedQrGeneratorServer) mustEmbedUnimplementedQrGeneratorServer() {}

// UnsafeQrGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QrGeneratorServer will
// result in compilation errors.
type UnsafeQrGeneratorServer interface {
	mustEmbedUnimplementedQrGeneratorServer()
}

func RegisterQrGeneratorServer(s grpc.ServiceRegistrar, srv QrGeneratorServer) {
	s.RegisterService(&QrGenerator_ServiceDesc, srv)
}

func _QrGenerator_GenerateQR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QrGenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QrGeneratorServer).GenerateQR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/qrgen.QrGenerator/GenerateQR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QrGeneratorServer).GenerateQR(ctx, req.(*QrGenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QrGenerator_ServiceDesc is the grpc.ServiceDesc for QrGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QrGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "qrgen.QrGenerator",
	HandlerType: (*QrGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateQR",
			Handler:    _QrGenerator_GenerateQR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qrgen.proto",
}
